### ISSUE TITLE
Links retrieved from the attribute article_url returns 404s

### ISSUE THREAD

**Issue by hoyce** [Nehle/open-shl#2]
Hi!

When retrieving articles from the `/articles` route in the API the `article_url` attribut is not correct.
I suppose the last path segment should be omitted. Eg. 

[http://www.frolundaindians.com/artikel/5tr4aithl-24601/premiarseger](http://www.frolundaindians.com/artikel/5tr4aithl-24601/premiarseger) should be [http://www.frolundaindians.com/artikel/5tr4aithl-24601/](http://www.frolundaindians.com/artikel/5tr4aithl-24601/)

Thanks for a really great API!

/ Niklas

**Comment by Nehle** [comment]
Thanks for your feedback. Unfortunately, that seems to be a data issue on the backend (Not sure if the Frölunda organization or the API is at fault though). This is only an unofficial client, so my ability to correct the issue is very limited. I suggest shooting an email to support@shl.se, to get the issueto the maintainers of the  actual API, and in the meantime have the consumer of the API transform the incoming data

Thanks
Jakob

**Comment by hoyce** [comment]
Ok, I see. I'll contact support@shl.se.

Thanks
Niklas
